/*
 * Copyright (C) 2013 NEC CASIO Mobile Communications, Ltd.
 *
 *  No permission to use, copy, modify and distribute this software
 *  and its documentation for any purpose is granted.
 *  This software is provided under applicable license agreement only.
 */

















#ifndef CAMERA_FUNCTION_H
#define CAMERA_FUNCTION_H

#if 1

#define FEATURE_DVE021_CAMERA_CONTINUOUS_AF

#define FEATURE_DVE021_CAMERA_FACE_DETECT

#define FEATURE_DVE021_CAM_SHAKE_RESISTANT

#define FEATURE_DVE021_CAM_QUICK_SHOT

#define FEATURE_DVE021_CAM_AUTO_SCENE_PICT



#define FEATURE_DVE021_CAM_SETTING

#define FEATURE_DVE021_CAM_SELF_TIMER

#define FEATURE_DVE021_CAM_CONTINUOUS_SHOOT

#define FEATURE_DVE021_CAM_MOBILE_LIGHT




#define FEATURE_DVE021_CAM_EXIF

#define FEATURE_DVE021_CAM_SOUND_PREVENT_PEEPING




#endif


#define DVE005_CAMERA_DRV     
#define DVE021_CAM_IPL_ENABLED



#define FEATURE_DVE021_CAM_DRV


#define FEATURE_DVE021_CAM_ESD_MEASURES_ENABLE


#define FEATURE_DVE021_CAMERA_ENABLE


#undef FEATURE_DVE021_CAM_NV_ENABLE








#define FEATURE_DVE021_CAM_MT9M113
#define CONFIG_FEATURE_DVE021_CAM_MT9M113

#define FEATURE_DVE021_CAM_MCLK_ENABLE
#define CONFIG_FEATURE_DVE021_CAM_MCLK_ENABLE







#define FEATURE_DVE021_CAM_SPIDER
#ifdef FEATURE_DVE021_CAM_SPIDER
  
  #define FEATURE_DVE021_CAM_MCLK_ENABLE
  
  #define FEATURE_DVE021_CAM_SPI_ENABLE
  
  #define FEATURE_DVE021_CAM_ISP_THREAD
  
  #define FEATURE_DVE021_CAM_STOP_OUTPUT
  
  #define FEATURE_DVE021_CAM_GB_BOOT_SENSOR
  

  
  #define FEATURE_DVE021_CAM_READ_FILE
  
  #define FEATURE_DVE021_CAM_PIC_SIZE_13M

  
  #define FEATURE_DVE021_CAM_ISP_DVE056
  
  #define FEATURE_DVE021_CAM_MT9M113
#endif 







#ifdef CONFIG_FEATURE_DVE021_CAM_SHAKE_RESISTANT
  
  #define D_IMAGE_SHAKE_FUNCTION
  
  #undef D_MOVIE_SHAKE_FUNCTION_REDUCTION
  
  #define D_MOVIE_SHAKE_FUNCTION
  #ifdef FEATURE_DVE021_COMPILE_ERR_ENABLE
    #define D_IMAGE_SHAKE_FUNCTION_COMPILE_ERROR
    #define D_MOVIE_SHAKE_FUNCTION_COMPILE_ERROR
  #endif
  #ifdef FEATURE_DVE021_TEST_PROGRAM

  #endif
#endif  


#ifdef CONFIG_FEATURE_DVE021_CAM_CONTINUOUS_SHOOT
  #define CONTINUOUS_SHOOT
  #define CONTINUOUS_SHOOT_RECEIVE_NOTIFY
  #ifdef FEATURE_DVE021_COMPILE_ERR_ENABLE
    #define CONTINUOUS_SHOOT_COMPILE_ERROR
  #endif
  #ifdef FEATURE_DVE021_TEST_PROGRAM
    #define CONTINUOUS_SHOOT_TEST_PROGRAM
    #define CONTINUOUS_SHOOT_RECEIVE_NOTIFY_TEST_PROGRAM
  #endif




#endif 


#ifdef CONFIG_FEATURE_DVE021_CAM_QUICK_SHOT
  
  #undef DVE005_INTERLEAVE_MODE_ENABLE
  #define QUICK_SHOOT
#else   
  
  #define DVE005_INTERLEAVE_MODE_ENABLE
#endif  


#ifdef CONFIG_FEATURE_DVE021_CAMERA_CONTINUOUS_AF
  #define FEATURE_DVE021_CAMERA_CONTINUOUS_AF
  #ifdef FEATURE_DVE021_TEST_PROGRAM
    #define FEATURE_DVE021_CAMERA_CONTINUOUS_AF_TEST_PROGRAM
  #endif
  #ifdef FEATURE_DVE021_COMPILE_ERR_ENABLE
    #define FEATURE_DVE021_CAMERA_CONTINUOUS_AF_COMPILE_ERROR
  #endif
#endif


#ifdef CONFIG_FEATURE_DVE021_CAM_MOBILE_LIGHT
  #ifdef FEATURE_DVE021_COMPILE_ERR_ENABLE
    #define FEATURE_DVE021_CAM_MOBILE_LIGHT_COMPILE_ERROR
  #endif
#endif  


#ifdef CONFIG_FEATURE_DVE021_CAM_EXIF

#endif


#ifdef FEATURE_DVE021_CAM_SHAKE_REDUCTION
  #ifdef FEATURE_DVE021_COMPILE_ERR_ENABLE_DVE043
    #define FEATURE_DVE021_CAM_SHAKE_REDUCTION_COMPILE_ERROR
  #endif
#endif 


#ifdef CONFIG_FEATURE_DVE021_DVE083
  #define FEATURE_DVE021_CAMERA_DVE084
  #ifdef FEATURE_DVE021_COMPILE_ERR_ENABLE
    #define FEATURE_DVE021_CAMERA_DVE084_COMPILE_ERROR
  #endif
#endif

  


  






  #define WHITEBALANCE

  
  #define FLICKER_REDUCTION


  #define D_SCENE_CHANGE_FUNCTION
  #ifdef FEATURE_DVE021_COMPILE_ERR_ENABLE
    #define D_SCENE_CHANGE_FUNCTION_COMPILE_ERROR
  #endif


  #define D_CAMERA_MODE_FUNCTION
  #ifdef FEATURE_DVE021_COMPILE_ERR_ENABLE
    #define D_CAMERA_MODE_FUNCTION_COMPILE_ERROR
  #endif

















  
  #define FEATURE_DVE021_CAMERA_BRIGHTNESS

  
  #define FEATURE_DVE021_CAMERA_ISO
  #ifdef FEATURE_DVE021_COMPILE_ERR_ENABLE
    #define FEATURE_DVE021_CAMERA_ISO_COMPILE_ERROR
  #endif

  
  #define FEATURE_DVE021_CAM_ZOOM

  
  #define FEATURE_DVE021_CAM_EFFECT

  

  
  


  
  #define FEATURE_DVE021_DVE042_ENABLE
  
  
  #define FEATURE_DVE021_LED_AUTO
  

  
  #define FEATURE_DVE021_DVE068_DVE042
  

  
  #undef FEATURE_DVE021_DVE039_PJ_DVE020
  #define FEATURE_DVE021_DVE039_PJ_REG

  
  #define FEATURE_DVE021_CAM_JPEG_RE_ENCODE


  
  #define FEATURE_DVE021_CAMERA_HDR


  


  


  


  


  


  


 


  
  #define FEATURE_DVE021_CAM_FASTBOOT
#endif 
